// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjghprorvtaolekxeiyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZ2hwcm9ydnRhb2xla3hlaXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTgxMjcsImV4cCI6MjA2NTQ5NDEyN30.tV06qXeLd00ZJDZnbtx1E6it_bbG_docjPh1Vgu8K9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);